apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" #Empty string must be explicitly set otherwise default storage class will be set
  volumeName: ebs-static # PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi