kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-030bdffcb630aaea7 # manually created efs id
  derectoryPerms: "700"
  basePath: "/expense"