kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    buildurl: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "hhtp://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx