kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # sft limit
      requests:
        memory: "68Mi"
        cpu: "100m"
      # hard limit
      limit:
        memory: "128Mi"
        cpu: "150m"