apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # lables of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80